# Generated by Django 4.1.7 on 2023-03-04 18:30

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='clients/'),
        ),
    ]
