# Generated by Django 4.1.7 on 2023-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterScript',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('script', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Insert Footer Script',
            },
        ),
        migrations.CreateModel(
            name='HeaderScript',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('script', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Insert Header Script',
            },
        ),
    ]
