# Generated by Django 4.1.7 on 2023-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebApproachContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Section One',
            },
        ),
        migrations.CreateModel(
            name='WebApproachSeoSnippets',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='WebApproachSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='about-slider/')),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb Image',
            },
        ),
    ]
