# Generated by Django 4.1.7 on 2023-04-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_approach', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webapproachcontent',
            options={'verbose_name_plural': 'Web Approach Content'},
        ),
    ]
