# Generated by Django 4.1.7 on 2023-04-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_approach', '0002_alter_webapproachcontent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
