# Generated by Django 4.1.7 on 2023-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_approach', '0003_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapproachcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webapp/'),
        ),
        migrations.AlterField(
            model_name='webapproachslider',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='webapp-slider/'),
        ),
    ]
