# Generated by Django 4.1.7 on 2023-03-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSeoSnippets',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='ContactSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='about-slider/')),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb Image',
            },
        ),
    ]
