# Generated by Django 4.1.7 on 2023-03-05 12:14

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ser_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', imagekit.models.fields.ProcessedImageField(upload_to='service/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Our Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceSeoSnippets',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='ServiceSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='service-slider/')),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb Image',
            },
        ),
    ]
