# Generated by Django 4.1.7 on 2023-03-05 12:33

import django.core.validators
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(upload_to='service/', validators=[django.core.validators.FileExtensionValidator('pdf', 'doc', 'svg')]),
        ),
    ]
