# Generated by Django 4.1.7 on 2023-03-05 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(upload_to='service/', validators=[django.core.validators.FileExtensionValidator('pdf', 'doc', 'svg')]),
        ),
    ]
