# Generated by Django 4.1.7 on 2023-03-05 15:30

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(upload_to='service/'),
        ),
    ]
