# Generated by Django 4.1.7 on 2023-03-07 08:57

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=155)),
                ('meta_tags', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(upload_to='blogimage/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSeoSnippets',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='BlogSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='about-slider/')),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb Image',
            },
        ),
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='authimage/')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=80)),
                ('meta_tags', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(upload_to='category/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Blog Comments',
                'ordering': ('add_date',),
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postauthor'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory'),
        ),
    ]
