# Generated by Django 4.1.7 on 2023-05-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='slug',
            new_name='cat_slug',
        ),
    ]
