# Generated by Django 4.1.7 on 2023-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='icon/')),
                ('facebook', models.URLField(blank=True, max_length=100)),
                ('instagram', models.URLField(blank=True, max_length=100)),
                ('linkedIn', models.URLField(blank=True, max_length=100)),
                ('twitter', models.URLField(blank=True, max_length=100)),
                ('contact', models.TextField()),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='home-slider/')),
                ('video_url', models.URLField(blank=True, max_length=300)),
            ],
        ),
    ]
