# Generated by Django 4.1.7 on 2023-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedIn',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
