# Generated by Django 4.1.7 on 2023-04-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_sitesetting_facebook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='instagram',
            new_name='discord',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='linkedIn',
            new_name='youtube',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='twitter',
        ),
    ]
