# Generated by Django 4.1.7 on 2023-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutcontentone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontentone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
