# Generated by Django 4.1.7 on 2023-02-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutcontentone_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContentTwo',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('sub_heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
