# Generated by Django 4.1.7 on 2023-02-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutcontenttwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutcontentone',
            options={'verbose_name_plural': 'About Section One'},
        ),
        migrations.AlterModelOptions(
            name='aboutcontenttwo',
            options={'verbose_name_plural': 'About Section Two'},
        ),
        migrations.AlterModelOptions(
            name='aboutslider',
            options={'verbose_name_plural': 'About Breadcrumb'},
        ),
    ]
