# Generated by Django 4.1.7 on 2023-02-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aboutseosnippets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutseosnippets',
            options={'verbose_name_plural': 'SEO'},
        ),
        migrations.AlterModelOptions(
            name='aboutslider',
            options={'verbose_name_plural': 'Breadcrumb Image'},
        ),
        migrations.AlterModelOptions(
            name='progressbar',
            options={'verbose_name_plural': 'Progress Bar'},
        ),
    ]
