# Generated by Django 4.1.7 on 2023-02-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_aboutseosnippets_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutseosnippets',
            options={'verbose_name_plural': 'About SEO'},
        ),
    ]
