# Generated by Django 4.1.7 on 2023-02-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_aboutseosnippets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutseosnippets',
            options={'verbose_name_plural': 'SEO'},
        ),
    ]
