# Generated by Django 4.1.7 on 2023-02-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clients/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=80)),
                ('meta_tags', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(upload_to='category/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSeoSnippets',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='about-slider/')),
            ],
            options={
                'verbose_name_plural': 'Breadcrumb Image',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tm_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('meta_description', models.CharField(max_length=155)),
                ('meta_tags', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('service', models.CharField(max_length=200, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliocategory')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.clients')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.team')),
            ],
        ),
    ]
