# Generated by Django 4.1.7 on 2023-02-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolioseosnippets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioseosnippets',
            options={'verbose_name_plural': 'SEO'},
        ),
    ]
